# Generated by Django 2.1.1 on 2018-09-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('domain_rule', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('cate', models.ForeignKey(on_delete=False, to='front.Cloud')),
            ],
        ),
        migrations.CreateModel(
            name='FreshLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=120)),
                ('freshtime', models.DateTimeField(auto_now=True)),
                ('cate', models.ForeignKey(on_delete=False, to='front.Cloud')),
                ('name', models.ForeignKey(on_delete=False, to='front.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='FreshStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('pwd', models.CharField(max_length=320)),
                ('addtime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logintime', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=False, to='front.User')),
            ],
        ),
        migrations.AddField(
            model_name='freshlog',
            name='state',
            field=models.ForeignKey(on_delete=False, to='front.FreshStatus'),
        ),
        migrations.AddField(
            model_name='freshlog',
            name='user',
            field=models.ForeignKey(on_delete=False, to='front.User'),
        ),
    ]
