# Generated by Django 2.1.1 on 2018-09-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshlog',
            name='task_id',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
